ktor:
  application:
    modules:
      - ee.carota.api.ApplicationKt.module
      - ee.carota.api.module.auth.AuthModuleKt.authModule
  deployment:
    port: $API_PORT
bcrypt:
  cost: $API_BCRYPT_COST
postgres:
  url: $API_POSTGRES_URL
  username: $API_POSTGRES_USERNAME
  password: $API_POSTGRES_PASSWORD
