services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - $JAEGER_QUERY_PORT:16686
      - $JAEGER_OTEL_HTTP_PORT:4318
    volumes:
      - type: tmpfs
        target: /tmp

volumes:
  postgres-data:
