services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
